msg = {
  db_success: "Successfully connected to the database",
  registered: "Successfully Registered",
  empty_first_name: "Please fill your Frist Name",
  register_first: "Register to continue !",
  empty_mobile: "Plase fill your mobile number",
  empty_email: "Please fill your email",
  empty_password: "Please fill your password",
  empty_locality:"Please fill your locality",
  empty_pincode:"Please fill your pincode",
  empty_ps:"Please fill your ps",
  empty_district:"Please fill your district",
  empty_state:"Please fill your state",
  empty_database_id:"Please enter database id",
  incorrect_mobile: "Please fill correct mobile of 10 digits",
  incorrect_email: "Please fill correct email",
  incorrect_password: "Please write proper password, Password must contain: Atleast 8 characters, 1 small, 1 captial and No spaces",
  enter_mobile: "Please enter mobile number to login",
  enter_password: "Please enter password to login",
  registered: "Successfully Registered",
  logedIn: "Successfully Loged In",
  logInError: "Mobile and Password doesnot match",
  getDataError: "User id and Password doesnot match",
  wrong_database_id:"Wrong Database id entered",
  databaseCustomerIdError:"Database id and Customer id doesnot match"
}
module.exports = msg;
